### ISSUE TITLE
Early stopping

### ISSUE THREAD

**Issue by JokingHero** [pinellolab/CRISPRitz#1]
Hi,

I find this software potentially useful and I would add this to my future pipeline. Is it difficult/possible to add an early stopping option which would limit number of reported off-targets per guide? The logic here is that there is no value in a guide that already has more than N off-targets.

Ideally this would report off-targets with low mismatch/gap first. Is it possible?

Best,
Kornel

**Comment by JokingHero** [comment]
After thinking about this a bit longer, I think it would be best to have something like "stop searching for this guide off-targets if:
1. You find #N1 offtargets with 0 levenshtein distance OR 
2. You find #N2 offtargets with 1 levenshtein distance OR 
3. You find #N3 offtargets with 2 levenshtein distance OR ...

**Comment by samuelecancellieri** [comment]
Hi,
sorry for the late response, but I did not receive any message from GitHub.
Your request is interesting but for now we have no internal counter for the number of off-target found for each input guide.
We can think about introducing that feature in a future update.

Thanks a lot for the suggestion.
