### ISSUE TITLE
-score question?

### ISSUE THREAD

**Issue by woodoo46** [pinellolab/CRISPRitz#10]
Hi there,

I am wondering how the -score works only for NGG or I need to tweak it for some other PAM?

Thanks.

George

**Comment by samuelecancellieri** [comment]
hi @woodoo46 
sorry for the late response.
the score, as stated in https://www.nature.com/articles/nbt.3437 is tested with spCas9 NGG PAM and so i will suggest you to not use it with different PAMs.

thanks
