### ISSUE TITLE
how was the annotation derived?

### ISSUE THREAD

**Issue by Huanle** [pinellolab/CRISPRitz#12]
Hi @lucapinello ,

May I ask how the annotation [file](https://github.com/pinellolab/CRISPRitz/blob/master/test_scripts/hg38Annotation.zip) - [hg38Annotation.zip](https://github.com/pinellolab/CRISPRitz/blob/master/test_scripts/hg38Annotation.zip) was derived? 

Thanks a lot.

**Comment by samuelecancellieri** [comment]
hi @Huanle 
the main source for the annotations are annotated gtf file for exons and http://genome.ucsc.edu/cgi-bin/hgTables for cCREs, DNAse and regulatory elements in general.
you just need to extract chromosome, start & end position of the element and give it a name you want to read in the results.
e.g., 
chr 1 1000 1100 exon

hope this help
best,

**Comment by Huanle** [comment]
> hi @Huanle the main source for the annotations are annotated gtf file for exons and http://genome.ucsc.edu/cgi-bin/hgTables for cCREs, DNAse and regulatory elements in general. you just need to extract chromosome, start & end position of the element and give it a name you want to read in the results. e.g., chr 1 1000 1100 exon
> 
> hope this help best,

Thanks a lot @samuelecancellieri . this is helpful.
