### ISSUE TITLE
PAM mismatch and gaps support

### ISSUE THREAD

**Issue by ofiryaish** [pinellolab/CRISPRitz#4]
Hey, 

Do you support mismatches and bulges in the PAM? I tried to run the tool and it seems that it does not handle this.  Even when I trying to index the genome with NNN PAM (meaning that when I will perform a search for off-targets so that it would take into account all possible PAMs in the DNA sequences), and performing the search for off-targets with NGG PAM, the tool forced the PAM of my guide to be NNN in order to avoid mismatches in the PAM.

Another question:
Does your tool support bulges in both DNA and RNA simultaneously?

Thank you

**Comment by samuelecancellieri** [comment]
Hi,
thanks for using the tool.

Regarding the PAM mismatches, we do not support mismatches in the PAM, if you search with NNN and generate the index with it, the tool will find any possible sequence but not reporting mismatches in the PAM sequence.
Regarding the DNA+RNA bulges, no, we support only type of bulge in a specific target, you can have the same target reported with both in different alignments but not both in the same target.

Thanks a lot for using the tool, if you have any more question, let me know.

Best
