### ISSUE TITLE
how to generate annotation file for other species

### ISSUE THREAD

**Issue by Huanle** [pinellolab/CRISPRitz#6]
Hi There,

Can you tell me how you generated the annotation file -- `hg38Annotation.zip`?

Thanks a lot.

**Comment by samuelecancellieri** [comment]
Hi @Huanle 
the file is generated starting for a gtf o gff, for example this one https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz

You just need to extract the chromosome, start, end and adding a 4th column with the annotation (CTCF, DNAse, Intron, Exon, etc).

Best,
SamuelE

**Comment by Huanle** [comment]
thanks a lot @samuelecancellieri

**Comment by lucapinello** [comment]
We used GENCODE and the ENCODE projects to gather and compile the
annotations we provide in CRISPRme.

**Comment by Huanle** [comment]
Thanks a lot Luca.
