### ISSUE TITLE
Calculating Start and End Positions

### ISSUE THREAD

**Issue by bcantarel** [pinellolab/CRISPRitz#9]
Based on the position field -- how would one figure out the start and end positions from the search output. Is it dependent on strand ie start = pos and end = pos+length of guide+pam for + strand and start = pos-length of guide-pam and end = pos for + strand?  Thanks!

**Comment by JAMKuttan** [comment]
I have this question too.

**Comment by samuelecancellieri** [comment]
hi @bcantarel and @JAMKuttan 
the position field always represent the first nt of the sequence reported as target.
if the PAM sequence is downstream the guide (e.g., cas9), when a target is reported as + strand, the position is the first nt of the target. if the target is - strand, the position is the first nt of the reported target but reverse complemented.
the position also account for bulges.
if the pam is upstream the guide (e.g., cas12) the position always report the first nt of the target, but the reverse complement is done on the + strand targets.
the end position is not reported by the software, but you can count it by adding the length of the complete guide+PAM.

let me know if this clarify the doubt.

best,
Samuele

**Comment by JAMKuttan** [comment]
Yes. thank you very much. The - strand was the biggest concern in this question.
